export interface BlogPost {
  id: string
  title: string
  excerpt: string
  content: string[]
  date: string
  readTime: string
  category: string
  imageUrl: string
}

export const blogPosts: BlogPost[] = [
  {
    id: 'phase-5-adaboost-cpp-integration',
    title: 'Phase 5 Complete: AdaBoost C++ Integration & Live GUI Verification',
    excerpt: 'We successfully exported our trained Python AdaBoost model directly into the OMNeT++ C++ core, enabling sub-microsecond Trust Evaluation and live GUI verification.',
    content: [
      'Today (September 3, 2026), we reached the ultimate milestone: embedding our Machine Learning intelligence directly into the C++ simulation core!',
      'Previously, our ML models ran offline in Python. To achieve real-time Edge computing, we wrote a script to export the exact decision stumps, weights, and feature scalers from our trained Python AdaBoost model straight into a C++ header (AdaBoostPredictor.h).',
      'The Roadside Unit (RSU) now evaluates every incoming BSM in sub-microsecond time using a Hybrid Decision Engine. If the historical trust score drops below 0.40 AND the AdaBoost model flags the packet, it is instantly BLOCKED.',
      'Furthermore, we brought the simulation to life visually in the OMNeT++ Qtenv GUI. Malicious vehicles now turn red and pop speech bubbles announcing their specific attacks (e.g., "FDI: Crash on Intersection! Stop!"). In response, the RSU pops bubbles announcing its ML verdicts (e.g., "AdaBoost: BLOCK! [V5 Mal 72%]").',
      'Finally, we implemented true Vehicle-to-Infrastructure (V2I) defense. When the RSU blocks an attacker, it broadcasts an IEEE 802.11p Road Safety Advisory back to the honest (green) vehicles, instructing their local OBUs to blacklist the rogue node. This perfectly demonstrates our decentralized Edge Trust network in action!'
    ],
    date: 'Sep 3, 2026',
    readTime: '5 min read',
    category: 'Milestone',
    imageUrl: 'https://images.unsplash.com/photo-1558494949-ef010cbdcc31?q=80&w=2034&auto=format&fit=crop',
  },
  {
    id: 'obu-level-trust-validation',
    title: 'OBU-Level Trust Validation: Local Verification at the Edge',
    excerpt: 'We extended the Trust Framework directly into the On-Board Units (OBUs), introducing a lightweight local filter to instantly drop malicious False Data Injection attacks.',
    content: [
      'Today (August 11, 2026), we successfully pushed our EdgeTrust framework down to the vehicle level!',
      'Until now, our On-Board Units (OBUs) were essentially passive relays—they broadcasted telemetry and blindly received messages, relying entirely on the heavy Machine Learning inference happening at the Roadside Unit (RSU) to protect the network.',
      'To minimize communication overhead and reduce malicious message propagation, we introduced a new Local Verification Layer directly into the OBU C++ codebase (EdgeTrustVehicleApp).',
      'Because OBUs have strictly limited processing power, we did not force them to run complex Random Forest algorithms. Instead, they act as the fast-response first line of defense. We built a lightweight kinematic physics check that executes the millisecond an OBU receives a Basic Safety Message (BSM).',
      'If the received packet claims physically impossible data—such as an attacker trying to inject a 0 m/s speed while being 150 meters away—the receiving OBU instantly flags the sender as suspicious and drops the packet. It does not forward it, and it does not process it further.',
      'By dropping these blatant False Data Injection (FDI) attacks locally, we drastically reduce bandwidth consumption and stop the attack from propagating across the VANET grid.'
    ],
    date: 'Aug 11, 2026',
    readTime: '3 min read',
    category: 'Milestone',
    imageUrl: 'https://images.unsplash.com/photo-1549317661-bd32c8ce0db2?q=80&w=2070&auto=format&fit=crop',
  },
  {
    id: 'phase-4-ml-hybrid-trust',
    title: 'Phase 4 Complete: Hybrid Machine Learning Trust Model Integration',
    excerpt: 'We successfully integrated our Random Forest Machine Learning pipeline with the temporal Trust Engine, proving that our Hybrid architecture can accurately detect and isolate malicious vehicular nodes.',
    content: [
      'Today (August 2, 2026), we reached an incredible milestone: The completion of Phase 4!',
      "In this phase, we took the raw telemetry data generated by our OMNeT++ simulations and fed it into our Python-based Machine Learning pipeline. Instead of relying on rigid, hardcoded mathematical weights to evaluate a vehicle's trustworthiness, we trained a Random Forest Classifier to mathematically deduce the optimal feature importance using Gini Impurity.",
      'The Hybrid Architecture:',
      'Our model does not just spit out a generic "trusted" or "malicious" label. Instead, the Random Forest outputs a probability (e.g., a 30% chance the packet is honest). We then feed this ML Evidence Score into our custom Hybrid Trust Engine.',
      "The Trust Engine uses an Exponential Moving Average (with an optimized forgetting factor of α=0.7) to blend the current ML Evidence with the vehicle's historical reputation. This prevents the system from accidentally isolating a vehicle due to a single noisy packet (like a momentary GPS dropout), while guaranteeing that persistent attackers are permanently blocked from the network.",
      'During our final simulation run, we watched the model perfectly detect an attacker. The Trust Score gracefully decayed from 1.0 down to a BLOCKED status over a span of exactly 6 packets, validating our exact mathematical proofs!',
      'Our next and final major step will be Phase 5: integrating Blockchain to securely share these computed trust scores across multiple RSUs.'
    ],
    date: 'Aug 2, 2026',
    readTime: '4 min read',
    category: 'Milestone',
    imageUrl: 'https://images.unsplash.com/photo-1555949963-ff9fe0c870eb?q=80&w=2070&auto=format&fit=crop',
  },
  {
    id: 'phase-3-trust-framework-implementation',
    title: 'Phase 3 Milestone: Malicious Node Injection & RSU Trust Evaluation',
    excerpt: 'We successfully implemented the Trust Evaluation logic directly into the OMNeT++ Roadside Units (RSUs) and injected False Data Injection (FDI) behaviors into malicious vehicles.',
    content: [
      'Today (July 28, 2026) marks the completion of the core C++ simulation portion of Phase 3!',
      'We modified the EdgeTrustVehicleApp to assign 25% of the simulated vehicles as malicious nodes. These rogue vehicles execute False Data Injection (FDI) attacks by broadcasting falsified Basic Safety Messages (BSMs), such as faking their GPS coordinates or reporting sudden 0 m/s speeds to cause phantom traffic jams.',
      'Simultaneously, we implemented the Edge Intelligence directly onto the EdgeTrustRSUApp. Our Roadside Units now actively track every vehicle\'s history and calculate their Physical Plausibility (kinematics) and Message Consistency. These features are fused into a rolling Trust Score.',
      'During our test runs, we watched the RSUs successfully catch the malicious nodes in real-time! The RSUs correctly penalized the fake GPS data, tanked the malicious nodes\' trust scores near zero, and issued immediate BLOCK verdicts. All of this telemetry is now streaming to a CSV dataset, perfectly setting the stage for our upcoming Python Machine Learning integration.'
    ],
    date: 'Jul 28, 2026',
    readTime: '3 min read',
    category: 'Milestone',
    imageUrl: 'https://images.unsplash.com/photo-1526374965328-7f61d4dc18c5?q=80&w=2070&auto=format&fit=crop',
  },
  {
    id: 'multi-density-traffic-analysis',
    title: 'Phase 2 Complete: Multi-Density Traffic Simulation & Performance Analysis',
    excerpt: 'We successfully simulated Low, Medium, and High traffic densities in SUMO and analyzed the resulting V2V and V2I network performance metrics in OMNeT++.',
    content: [
      'Today (July 20, 2026), we successfully completed the final objectives of Phase 2!',
      'While basic simulation proved our architecture works, real-world VANETs operate under wildly varying conditions. To rigorously test our network\'s scalability and reliability, we generated three distinct traffic profiles in SUMO:',
      '1. Low Density: Sparse, isolated vehicle movement to establish a perfect-communication baseline.',
      '2. Medium Density: Standard urban traffic to test typical DSRC message exchanges between vehicles and RSUs.',
      '3. High Density: Heavy congestion designed to saturate the wireless channel and induce packet collisions.',
      'Network Analysis and Metrics:',
      'By running these scenarios through OMNeT++, we successfully extracted critical communication metrics (Scalar and Vector data). The results allowed us to analyze Packet Propagation Delays and Packet Delivery Ratios (PDR). As expected, in High Density scenarios, the sheer volume of 802.11p broadcasts leads to increased channel contention and MAC-layer collisions.',
      'This multi-density dataset is exactly what our Trust Management system needs. By understanding normal network degradation (due to traffic), our upcoming Machine Learning models will be able to distinguish between natural packet loss and malicious blackhole attacks.',
      'Next, we move to Phase 3: Implementing the Edge Intelligence on our RSUs to detect these malicious behaviors!'
    ],
    date: 'Jul 20, 2026',
    readTime: '3 min read',
    category: 'Analysis',
    imageUrl: 'https://images.unsplash.com/photo-1494522855154-9297ac14b55f?q=80&w=2070&auto=format&fit=crop',
  },
  {
    id: 'sumo-veins-omnet-integration',
    title: 'Bridging the Gap: Successful SUMO, OMNeT++, and Veins Integration',
    excerpt: 'We achieved a major milestone today by establishing a bidirectional real-time bridge between our SUMO mobility traffic and the OMNeT++ network simulator using Veins. It wasn\'t easy, but we crushed the bugs!',
    content: [
      'Today (July 17, 2026) marks a massive achievement for the EdgeTrust-VANET team: Phase 3 is complete!',
      'We successfully established the TraCI (Traffic Control Interface) bridge, meaning the physical vehicles driving in SUMO are now perfectly mirrored as network nodes broadcasting 802.11p Wi-Fi packets inside OMNeT++.',
      'The Roadblocks We Overcame:',
      'This integration was far from plug-and-play. We had to perform deep-level surgical fixes on the simulators:',
      '1. TraCI API Version Mismatch: Our newer SUMO installation used TraCI API 22, but Veins 5.3 was hardcoded for API 20. We dove into the Veins C++ source code (TraCICommandInterface.cc), patched the version checks, and recompiled the core engine.',
      '2. Python Daemon Ghosting: The sumo-launchd python script was leaving orphaned processes battling for port 9999, causing OMNeT++ to connect to dead sockets. We purged the zombies and enforced clean socket binds.',
      '3. Obstacle Shadowing Crashes: The OMNeT++ radio physics engine crashed trying to compute signal bounce off missing buildings. We cleverly satisfied the engine by injecting a dummy obstacle XML completely out-of-bounds.',
      '4. Vehicle Spawning Desync: We debugged a timing flaw where OMNeT++ demanded vehicle physical coordinates milliseconds before TraCI could fetch them from SUMO. Supplying dummy (0,0,0) initialization vectors solved the crash.',
      'What We Learned:',
      'We learned that bidirectional coupling of complex legacy simulators requires a deep understanding of their internal timing, API protocols, and physical-to-digital mapping. Watching the first safety beacons transmit across our grid intersection made every bug worth it!',
      'Next, we will begin developing the Edge Server logic to start collecting telemetry for our Machine Learning models.'
    ],
    date: 'Jul 17, 2026',
    readTime: '4 min read',
    category: 'Milestone',
    imageUrl: 'https://images.unsplash.com/photo-1526374965328-7f61d4dc18c5?q=80&w=2070&auto=format&fit=crop',
  },
  {
    id: 'basic-traffic-simulation',
    title: 'Simulating Basic Traffic in SUMO & Connecting to OMNeT++',
    excerpt: 'Today we successfully simulated our first basic traffic scenarios in SUMO! Our next immediate step is to connect this mobility model with OMNeT++ using Veins to observe network packet behavior in real-time.',
    content: [
      'Welcome to today’s update (July 16, 2026)! We have reached an exciting milestone in the EdgeTrust-VANET project.',
      'Our focus today was entirely on the SUMO (Simulation of Urban MObility) environment. We took the Grid Road Network we designed previously and successfully injected our first basic traffic simulation.',
      'By defining vehicle types, randomized routes, and varying speeds, we were able to observe the microscopic mobility of nodes interacting within the grid. This is a critical step because realistic mobility is the foundation of any accurate VANET simulation.',
      'What’s Next?',
      'Our immediate next phase is Phase 3: SUMO–Veins Integration. We are going to connect this active SUMO traffic simulation with the OMNeT++ network simulator using the Veins framework. This will allow us to map each moving vehicle to a network node and observe wireless packet behavior (like beacons and safety messages) in real-time as they move around the grid.'
    ],
    date: 'Jul 16, 2026',
    readTime: '3 min read',
    category: 'Simulation',
    imageUrl: 'https://images.unsplash.com/photo-1449824913935-59a10b8d2000?q=80&w=2070&auto=format&fit=crop',
  },
  {
    id: 'grid-road-network',
    title: 'Designing the Grid Road Network',
    excerpt: 'We have mapped out and created a complex Grid Road Network inside SUMO. This will serve as our primary testing ground for intersection-based vehicular communication and potential sybil attacks.',
    content: [
      'On July 10, 2026, we finalized the spatial environment for our simulations.',
      'Using the NETEDIT tool provided by SUMO, we designed a custom Grid Road Network. A grid layout was chosen specifically because it offers multiple intersections, varied line-of-sight conditions, and highly dynamic routing options for the vehicles.',
      'Why a Grid Network?',
      'In VANETs, intersections are critical bottlenecks where safety messages must be broadcasted effectively. It is also where malicious nodes can do the most damage (e.g., broadcasting false congestion alerts to reroute traffic). By using a grid, we can rigorously test our Edge-based Machine Learning models and Trust Management systems against attacks like False Information Dissemination and Blackhole attacks.',
      'The network files have been saved and integrated into our simulation repository, ready for the upcoming traffic injection.'
    ],
    date: 'Jul 10, 2026',
    readTime: '4 min read',
    category: 'Environment',
    imageUrl: 'https://images.unsplash.com/photo-1555066931-4365d14bab8c?q=80&w=2070&auto=format&fit=crop',
  },
  {
    id: 'environment-setup',
    title: 'Development Environment & Toolchain Setup',
    excerpt: 'Phase 2 is officially underway. We have installed the required simulators (SUMO, OMNeT++, and Veins) on Windows 11 and established our GitHub organization for version control.',
    content: [
      'On July 5, 2026, we officially completed the setup of our simulation environment, marking the beginning of Phase 2.',
      'Our toolchain is heavily reliant on open-source, highly-regarded network and traffic simulators. Here is what we installed and configured on our Windows 11 development machines:',
      '1. SUMO (Simulation of Urban MObility): The industry standard for continuous, microscopic road traffic simulation.',
      '2. OMNeT++: A component-based C++ simulation library primarily used for building network simulators.',
      '3. Veins: The open-source framework that seamlessly links OMNeT++ with SUMO, enabling Inter-Vehicular Communication (IVC) simulations.',
      'In addition, we initialized our GitHub Organization (EdgeTrust-VANET) to ensure all configuration files, network maps, and Python ML scripts are properly version-controlled. We are now ready to start building the simulation world.'
    ],
    date: 'Jul 5, 2026',
    readTime: '2 min read',
    category: 'Setup',
    imageUrl: 'https://images.unsplash.com/photo-1550439062-609e1531270e?q=80&w=2070&auto=format&fit=crop',
  },
  {
    id: 'learning-sumo-omnet',
    title: 'Understanding SUMO and OMNeT++',
    excerpt: 'Spent this week learning the intricacies of SUMO for modeling microscopic vehicle mobility, and OMNeT++ for simulating the wireless network communication layers. Veins will be our bridge.',
    content: [
      'Over the past week (leading up to June 25, 2026), the team engaged in a deep-dive learning sprint.',
      'To build a realistic Behavioral Trust Management system, we need highly accurate simulations. We spent this time studying the documentation and running tutorials for our core simulation stack.',
      'SUMO: We learned how to define edges (roads), nodes (junctions), and vehicle flows. SUMO’s TraCI (Traffic Control Interface) will be particularly vital later on for manipulating vehicle behavior dynamically.',
      'OMNeT++: We explored its modular architecture, specifically focusing on the INET framework which models the OSI layers. Understanding how MAC layers handle packet collisions and delays is essential for extracting the communication features (like RSSI, Packet Delay, and Packet Loss) our Machine Learning models will rely on.',
      'Next up, we will install these tools natively and set up our repository.'
    ],
    date: 'Jun 25, 2026',
    readTime: '5 min read',
    category: 'Research',
    imageUrl: 'https://images.unsplash.com/photo-1519389950473-47ba0277781c?q=80&w=2070&auto=format&fit=crop',
  },
  {
    id: 'project-kickoff',
    title: 'Project Kickoff & Extensive Literature Survey',
    excerpt: 'We officially started EdgeTrust-VANET! Began with a deep dive into VANET security, analyzing over 285 peer-reviewed publications to understand the limitations of PKI and the need for behavioral trust.',
    content: [
      'June 15, 2026 marks the official kickoff of the EdgeTrust-VANET project!',
      'We started Phase 1 by conducting a massive literature survey, synthesizing insights from 285 peer-reviewed publications spanning from 2014 to 2026. Our goal was to identify the critical vulnerabilities in modern Vehicular Ad Hoc Networks.',
      'The Core Problem:',
      'Current VANET security relies heavily on Public Key Infrastructure (PKI). While PKI is excellent for verifying identity during authentication, it suffers from a fatal flaw: it cannot monitor a node’s behavior after it joins the network. If an authenticated vehicle goes rogue or gets compromised, PKI alone cannot stop it from launching insider attacks (like Sybil or Blackhole attacks).',
      'The Proposed Solution:',
      'Our architecture will push security to the Edge (Roadside Units). These RSUs will compute Trust Scores based on vehicle behavior (packet forwarding, mobility consistency, etc.) and run lightweight Machine Learning inference (using Random Forest/XGBoost) to detect anomalies in real-time.',
      'The literature review is complete, the architecture is designed, and the technology stack is selected. It’s time to start building.'
    ],
    date: 'Jun 15, 2026',
    readTime: '6 min read',
    category: 'Milestone',
    imageUrl: 'https://images.unsplash.com/photo-1451187580459-43490279c0fa?q=80&w=2072&auto=format&fit=crop',
  }
]
