export interface BlogPost {
  id: string
  title: string
  excerpt: string
  content: string[]
  date: string
  readTime: string
  category: string
  imageUrl: string
}

export const blogPosts: BlogPost[] = [
  {
    id: 'live-ml-dashboard-telemetry',
    title: 'Live ML Dashboard & Telemetry Evaluation Tools Released',
    excerpt: 'We have fully deployed the local ML Flask dashboard and added Python scripts to evaluate live OMNeT++ telemetry against all 9 of our machine learning models.',
    content: [
      'Today (September 4, 2026), we pulled in a massive update to our Machine Learning pipeline (edgetrust-ml)!',
      'We have officially released the Flask-based Web Dashboard. It runs locally and provides an interactive UI to analyze the live_extracted_features.csv generated by our OMNeT++ RSUs.',
      'Additionally, we introduced test_live_features.py, a powerful script that ingests the live telemetry and runs it against all our trained models (Random Forest, AdaBoost, SVM, Logistic Regression, etc.).',
      'The results are astonishing: Our models are hitting >96% accuracy on live, unseen data directly from the network simulator. This proves our dataset training perfectly mirrors the actual simulated physics!'
    ],
    date: 'Sep 4, 2026',
    readTime: '3 min read',
    category: 'Milestone',
    imageUrl: 'https://images.unsplash.com/photo-1551288049-bebda4e38f71?q=80&w=2070&auto=format&fit=crop',
  },
  {
    id: 'phase-5-adaboost-cpp-integration',
    title: 'Phase 5 Complete: AdaBoost C++ Integration & Live GUI Verification',
    excerpt: 'We successfully exported our trained Python AdaBoost model directly into the OMNeT++ C++ core, enabling sub-microsecond Trust Evaluation and live GUI verification.',
    content: [
      'Today (September 3, 2026), we reached the ultimate milestone: embedding our Machine Learning intelligence directly into the C++ simulation core!',
      'Previously, our ML models ran offline in Python. To achieve real-time Edge computing, we wrote a script to export the exact decision stumps, weights, and feature scalers from our trained Python AdaBoost model straight into a C++ header (AdaBoostPredictor.h).',
      'The Roadside Unit (RSU) now evaluates every incoming BSM in sub-microsecond time using a Hybrid Decision Engine. If the historical trust score drops below 0.40 AND the AdaBoost model flags the packet, it is instantly BLOCKED.',
      'Furthermore, we brought the simulation to life visually in the OMNeT++ Qtenv GUI. Malicious vehicles now turn red and pop speech bubbles announcing their specific attacks (e.g., "FDI: Crash on Intersection! Stop!"). In response, the RSU pops bubbles announcing its ML verdicts (e.g., "AdaBoost: BLOCK! [V5 Mal 72%]").',
      'Finally, we implemented true Vehicle-to-Infrastructure (V2I) defense. When the RSU blocks an attacker, it broadcasts an IEEE 802.11p Road Safety Advisory back to the honest (green) vehicles, instructing their local OBUs to blacklist the rogue node. This perfectly demonstrates our decentralized Edge Trust network in action!'
    ],
    date: 'Sep 3, 2026',
    readTime: '5 min read',
    category: 'Milestone',
    imageUrl: 'https://images.unsplash.com/photo-1558494949-ef010cbdcc31?q=80&w=2034&auto=format&fit=crop',
  },
  {
    id: 'exporting-adaboost-to-cpp',
    title: 'Exporting Scikit-Learn AdaBoost to C++ Arrays',
    excerpt: 'A deep dive into how we bypassed Python overhead by manually translating our trained AdaBoost model into raw C++ decision stumps.',
    content: [
      'Running Python during an OMNeT++ simulation creates massive overhead and socket lag. We needed our RSU to run the ML model natively in C++.',
      'To solve this, we wrote a custom export_adaboost_cpp.py script. This script digs into the Scikit-Learn AdaBoostClassifier object, extracts the 50 underlying DecisionTreeRegressor stumps, their weights, and the threshold values.',
      'It then formats them into a massive C++ header file (AdaBoostPredictor.h) using nested if/else arrays. This allows the RSU to perform sub-microsecond inference on every single packet locally!'
    ],
    date: 'Sep 2, 2026',
    readTime: '4 min read',
    category: 'Technical',
    imageUrl: 'https://images.unsplash.com/photo-1542831371-29b0f74f9713?q=80&w=2070&auto=format&fit=crop',
  },
  {
    id: 'visualizing-misclassified-packets',
    title: 'Visualizing Misclassified Packets in the UI',
    excerpt: 'How we used the dashboard to identify edge cases where honest vehicles were falsely flagged due to extreme GPS drift.',
    content: [
      'While our models boast high accuracy, False Positives are the enemy of VANETs. You cannot afford to ban an ambulance because its GPS glitched.',
      'Using our new Dashboard, we visualized the misclassified packets. We discovered that vehicles experiencing high acceleration at intersection corners were sometimes flagged as FDI by the Decision Tree.',
      'This is exactly why we rely on AdaBoost and the EMA (Exponential Moving Average)—the ensemble method correctly smoothed out these corner cases, ensuring honest vehicles are not unjustly isolated.'
    ],
    date: 'Aug 30, 2026',
    readTime: '3 min read',
    category: 'Analysis',
    imageUrl: 'https://images.unsplash.com/photo-1551288049-bebda4e38f71?q=80&w=2070&auto=format&fit=crop',
  },
  {
    id: 'deep-dive-into-fdi',
    title: 'The Deep Dive into False Data Injection (FDI)',
    excerpt: 'Understanding the mechanics of an FDI attack and how malicious nodes spoof traffic jams in our simulation.',
    content: [
      'False Data Injection (FDI) is the primary attack vector we are defending against. But how does it actually work in code?',
      'Inside our EdgeTrustVehicleApp, when a node is tagged as malicious, it alters the payload of its Basic Safety Message (BSM) right before hitting the MAC layer.',
      'It modifies its reported X/Y coordinates by +150 meters and forces its reported speed to 0.0 m/s. To the rest of the network, it looks like a severe crash has blocked a distant road, causing honest cars to reroute. This is exactly what our trust model detects and blocks!'
    ],
    date: 'Aug 25, 2026',
    readTime: '3 min read',
    category: 'Research',
    imageUrl: 'https://images.unsplash.com/photo-1526374965328-7f61d4dc18c5?q=80&w=2070&auto=format&fit=crop',
  },
  {
    id: 'live-simulation-telemetry',
    title: 'Live Simulation Features: Analyzing 20-Column Telemetry',
    excerpt: 'A breakdown of the 20 distinct network and physical features we extract from OMNeT++ to train our models.',
    content: [
      'Our CSV dataset is the lifeblood of our Machine Learning models. Every packet processed by the RSU logs exactly 20 features.',
      'These include Physical Features (Speed, Position X/Y, Heading, Acceleration) and Network Features (Packet Drop Ratio, Latency, Message Retransmissions, RSSI Signal Strength).',
      'By combining MAC-layer networking stats with application-layer physics, our Random Forest model can detect complex attacks that purely physical filters would miss.'
    ],
    date: 'Aug 20, 2026',
    readTime: '4 min read',
    category: 'Data',
    imageUrl: 'https://images.unsplash.com/photo-1551288049-bebda4e38f71?q=80&w=2070&auto=format&fit=crop',
  },
  {
    id: 'developing-ml-dashboard',
    title: 'Developing the ML Dashboard App with Flask',
    excerpt: 'Building the backend architecture to serve our machine learning insights to the browser.',
    content: [
      'To make our Machine Learning results accessible to the review panel, we needed a visual interface.',
      'We built a lightweight Flask backend (app.py) that loads the pickled Scikit-Learn models and exposes them via REST APIs.',
      'The dashboard allows users to upload a live CSV from OMNeT++, run inference, and instantly see accuracy comparisons across all 9 models on a beautiful web UI.'
    ],
    date: 'Aug 15, 2026',
    readTime: '3 min read',
    category: 'Development',
    imageUrl: 'https://images.unsplash.com/photo-1555099962-4199c345e5dd?q=80&w=2070&auto=format&fit=crop',
  },
  {
    id: 'obu-level-trust-validation',
    title: 'OBU-Level Trust Validation: Local Verification at the Edge',
    excerpt: 'We extended the Trust Framework directly into the On-Board Units (OBUs), introducing a lightweight local filter to instantly drop malicious attacks.',
    content: [
      'Today (August 11, 2026), we successfully pushed our EdgeTrust framework down to the vehicle level!',
      'Until now, our On-Board Units (OBUs) were essentially passive relays. To minimize communication overhead, we introduced a Local Verification Layer directly into the OBU C++ codebase.',
      'Because OBUs have strictly limited processing power, they do not run Random Forest. Instead, they act as the fast-response first line of defense using a lightweight kinematic physics check.',
      'If the received packet claims physically impossible data (>50 m/s speeds in a city), the receiving OBU instantly flags the sender and drops the packet. It does not forward it.',
      'By dropping these blatant FDI attacks locally, we drastically reduce bandwidth consumption and stop the attack from propagating across the VANET grid.'
    ],
    date: 'Aug 11, 2026',
    readTime: '3 min read',
    category: 'Milestone',
    imageUrl: 'https://images.unsplash.com/photo-1549317661-bd32c8ce0db2?q=80&w=2070&auto=format&fit=crop',
  },
  {
    id: 'vehicle-kinematics',
    title: 'Vehicle Kinematics: How we drop physically impossible packets',
    excerpt: 'The math behind the OBU lightweight filter that protects the network from blatant spoofing.',
    content: [
      'How does the OBU know a packet is fake without running Machine Learning?',
      "It uses basic high-school physics. The vehicle extracts the sender's stated velocity vector and compares it to the urban grid limits. If a car claims to be traveling at 60 m/s (134 mph) through a dense urban intersection, it is mathematically impossible.",
      'This simple if-statement acts as a powerful pre-filter, ensuring the RSU is not bogged down analyzing painfully obvious attacks.'
    ],
    date: 'Aug 10, 2026',
    readTime: '2 min read',
    category: 'Technical',
    imageUrl: 'https://images.unsplash.com/photo-1502877338535-766e1452684a?q=80&w=2072&auto=format&fit=crop',
  },
  {
    id: 'hyperparameter-tuning-alpha',
    title: 'Hyperparameter Tuning: Why Alpha = 0.7?',
    excerpt: 'Proving mathematically why an Exponential Moving Average forgetting factor of 0.7 is the perfect balance for VANETs.',
    content: [
      'In our Trust Engine, we use an Exponential Moving Average (EMA). The critical parameter is Alpha (α), which dictates how much we trust history vs. current evidence.',
      'If Alpha is 0.95, the system takes forever to ban an attacker. If Alpha is 0.20, the system bans honest vehicles over a single dropped packet.',
      'We ran a Grid Search optimization script against a custom Cost Function comparing False Isolation Rate vs Detection Delay. The graph perfectly intersected at exactly α = 0.7. This allows us to ban attackers in exactly 5 packets while absorbing momentary GPS noise.'
    ],
    date: 'Aug 8, 2026',
    readTime: '4 min read',
    category: 'Research',
    imageUrl: 'https://images.unsplash.com/photo-1509228468518-180dd4864904?q=80&w=2070&auto=format&fit=crop',
  },
  {
    id: 'implementing-ema',
    title: 'Implementing the Exponential Moving Average (EMA) Trust Equation',
    excerpt: 'Fusing Machine Learning probabilities with temporal history using time-series mathematics.',
    content: [
      'A machine learning model only evaluates a single packet in isolation. But trust is built over time.',
      'To give our RSU memory, we implemented the Exponential Moving Average equation: T_t = α*T_{t-1} + (1-α)*E_t.',
      'This mathematically guarantees that a vehicle cannot build up years of good trust and then suddenly launch an attack without consequence. The current evidence (E_t) will rapidly decay their score.'
    ],
    date: 'Aug 5, 2026',
    readTime: '3 min read',
    category: 'Technical',
    imageUrl: 'https://images.unsplash.com/photo-1635070041078-e363dbe005cb?q=80&w=2070&auto=format&fit=crop',
  },
  {
    id: 'phase-4-ml-hybrid-trust',
    title: 'Phase 4 Complete: Hybrid Machine Learning Trust Model Integration',
    excerpt: 'We successfully integrated our Random Forest pipeline with the temporal Trust Engine, proving our architecture detects malicious nodes.',
    content: [
      'Today (August 2, 2026), we reached an incredible milestone: The completion of Phase 4!',
      'Instead of relying on rigid, hardcoded mathematical weights, we trained a Random Forest Classifier to mathematically deduce optimal feature importance using Gini Impurity.',
      'The Random Forest outputs a probability (e.g., a 30% chance the packet is honest), which we feed into our EMA Trust Engine.',
      'During our final run, we watched the model perfectly detect an attacker, dropping their Trust Score to BLOCKED over exactly 6 packets!'
    ],
    date: 'Aug 2, 2026',
    readTime: '4 min read',
    category: 'Milestone',
    imageUrl: 'https://images.unsplash.com/photo-1555949963-ff9fe0c870eb?q=80&w=2070&auto=format&fit=crop',
  },
  {
    id: 'random-forest-vs-svm',
    title: 'Random Forest vs SVM: Why Ensemble Methods win',
    excerpt: 'A comparison of our trained models and why Random Forest heavily outperformed SVM on our VANET dataset.',
    content: [
      "While evaluating models, we noticed Support Vector Machines (SVM) struggled with our dataset, achieving only 88% accuracy compared to Random Forest's 96%.",
      'Why? Because VANET telemetry is highly non-linear. A speed of 0 m/s is normal at a traffic light, but malicious if happening in the middle of a highway. SVM struggles to draw linear hyperplanes through this logic.',
      'Random Forest handles conditional non-linear logic effortlessly via decision trees, making it the superior choice for Edge computing.'
    ],
    date: 'Jul 31, 2026',
    readTime: '3 min read',
    category: 'Analysis',
    imageUrl: 'https://images.unsplash.com/photo-1551288049-bebda4e38f71?q=80&w=2070&auto=format&fit=crop',
  },
  {
    id: 'addressing-blackhole-attacks',
    title: 'Addressing the Blackhole Attack Vector',
    excerpt: 'How we configured malicious nodes to intentionally drop packets and disrupt the routing topology.',
    content: [
      'While False Data Injection fakes data, Blackhole attacks destroy data. We programmed our malicious nodes to intentionally drop 70% of the packets they are supposed to route.',
      'By analyzing the packet_drop_ratio and message_retransmission_count features at the RSU, our Machine Learning model successfully identifies these blackholes and routes traffic around them.'
    ],
    date: 'Jul 29, 2026',
    readTime: '3 min read',
    category: 'Research',
    imageUrl: 'https://images.unsplash.com/photo-1526374965328-7f61d4dc18c5?q=80&w=2070&auto=format&fit=crop',
  },
  {
    id: 'phase-3-trust-framework-implementation',
    title: 'Phase 3 Milestone: Malicious Node Injection & RSU Trust Evaluation',
    excerpt: 'We successfully implemented Trust Evaluation directly into the OMNeT++ RSUs and injected FDI behaviors into malicious vehicles.',
    content: [
      'Today (July 28, 2026) marks the completion of the core C++ simulation portion of Phase 3!',
      'We assigned 25% of the simulated vehicles as malicious nodes executing FDI attacks.',
      "Simultaneously, we implemented Edge Intelligence onto the RSU. RSUs now actively track every vehicle's history and calculate Physical Plausibility and Message Consistency.",
      'During our test runs, we watched the RSUs successfully catch the malicious nodes, tanking their trust scores near zero and issuing BLOCK verdicts. All telemetry is now streaming to CSV!'
    ],
    date: 'Jul 28, 2026',
    readTime: '3 min read',
    category: 'Milestone',
    imageUrl: 'https://images.unsplash.com/photo-1526374965328-7f61d4dc18c5?q=80&w=2070&auto=format&fit=crop',
  },
  {
    id: 'designing-rsu-architecture',
    title: 'Designing the Roadside Unit (RSU) Architecture',
    excerpt: 'Positioning and configuring the 802.11p radio towers for maximum coverage at the urban intersection.',
    content: [
      'To build a true Edge network, the RSU placement is critical. We configured the RSU POI (Point of Interest) at coordinates x=76, y=41, perfectly centered at the 4-way grid intersection.',
      'We tuned the OMNeT++ PHY MAC layer parameters to ensure the transmission power cleanly cuts off at 250 meters. This ensures the RSU only processes relevant local traffic, adhering to Edge Computing principles.'
    ],
    date: 'Jul 26, 2026',
    readTime: '2 min read',
    category: 'Development',
    imageUrl: 'https://images.unsplash.com/photo-1519389950473-47ba0277781c?q=80&w=2070&auto=format&fit=crop',
  },
  {
    id: 'evaluating-sybil-attacks',
    title: 'Evaluating Sybil Attacks in Veins',
    excerpt: 'Injecting Sybil behaviors to test if our trust model can detect ghost vehicles.',
    content: [
      'A Sybil attack involves one physical vehicle broadcasting multiple fake identities (Ghost Vehicles) to create the illusion of heavy congestion.',
      'We modified the MAC layer in Veins to allow our malicious node to cycle through spoofed MAC addresses.',
      'Our physical plausibility check successfully flags this because multiple IDs are broadcasting the exact same X/Y coordinates simultaneously—an impossible physical state.'
    ],
    date: 'Jul 25, 2026',
    readTime: '3 min read',
    category: 'Research',
    imageUrl: 'https://images.unsplash.com/photo-1526374965328-7f61d4dc18c5?q=80&w=2070&auto=format&fit=crop',
  },
  {
    id: 'impact-high-density-pdr',
    title: 'The impact of High-Density Traffic on PDR',
    excerpt: 'Analyzing why Packet Delivery Ratios drop significantly during congestion.',
    content: [
      'During our High-Density stress tests, we noticed Packet Delivery Ratios (PDR) plummeted due to MAC-layer collisions on the 802.11p control channel.',
      'This is a crucial finding. If we blindly punish vehicles for dropping packets, we will ban honest vehicles during rush hour. Our Machine Learning model must learn to correlate PDR drops with high local vehicle density to avoid false positives.'
    ],
    date: 'Jul 24, 2026',
    readTime: '3 min read',
    category: 'Analysis',
    imageUrl: 'https://images.unsplash.com/photo-1494522855154-9297ac14b55f?q=80&w=2070&auto=format&fit=crop',
  },
  {
    id: 'parsing-sumo-xml-to-csv',
    title: 'Parsing SUMO XML outputs into CSV',
    excerpt: 'Building the data bridges required to feed C++ simulation logs into Python pandas.',
    content: [
      'OMNeT++ writes output natively to scalar and vector XML files, which are notoriously difficult to feed into Scikit-Learn.',
      'We wrote custom C++ output streams inside the RSU to bypass the scalar framework, writing directly to thread-safe CSV files formatted precisely for Pandas DataFrames. This saved hours of post-simulation processing!'
    ],
    date: 'Jul 22, 2026',
    readTime: '2 min read',
    category: 'Development',
    imageUrl: 'https://images.unsplash.com/photo-1555099962-4199c345e5dd?q=80&w=2070&auto=format&fit=crop',
  },
  {
    id: 'multi-density-traffic-analysis',
    title: 'Phase 2 Complete: Multi-Density Traffic Simulation & Analysis',
    excerpt: 'We successfully simulated Low, Medium, and High traffic densities in SUMO and analyzed the resulting V2V metrics.',
    content: [
      'Today (July 20, 2026), we successfully completed the final objectives of Phase 2!',
      "To rigorously test our network's scalability, we generated three distinct traffic profiles in SUMO: Low, Medium, and High Density.",
      'By running these through OMNeT++, we extracted critical metrics on Packet Propagation Delays and Packet Delivery Ratios (PDR).',
      'This multi-density dataset is exactly what our Trust Management system needs to distinguish between natural packet loss (rush hour) and malicious blackhole attacks!'
    ],
    date: 'Jul 20, 2026',
    readTime: '3 min read',
    category: 'Analysis',
    imageUrl: 'https://images.unsplash.com/photo-1494522855154-9297ac14b55f?q=80&w=2070&auto=format&fit=crop',
  },
  {
    id: 'overcoming-traci-socket-timeouts',
    title: 'Overcoming TraCI socket timeout issues',
    excerpt: 'Debugging the infamous Port 9999 zombie connection errors during Veins integration.',
    content: [
      'One of the hardest bugs we faced was the sumo-launchd.py script leaving orphaned processes battling for port 9999.',
      'OMNeT++ would attempt to connect to a dead socket, causing the entire simulation to crash immediately. We implemented strict TCP keep-alive checks and gracefully handled socket teardowns in the Python daemon to fix this permanently.'
    ],
    date: 'Jul 19, 2026',
    readTime: '3 min read',
    category: 'Development',
    imageUrl: 'https://images.unsplash.com/photo-1542831371-29b0f74f9713?q=80&w=2070&auto=format&fit=crop',
  },
  {
    id: 'sumo-veins-omnet-integration',
    title: 'Bridging the Gap: Successful SUMO, OMNeT++, and Veins Integration',
    excerpt: 'We established a bidirectional real-time bridge between our SUMO mobility traffic and OMNeT++ using Veins.',
    content: [
      'Today (July 17, 2026) marks a massive achievement: Phase 3 is complete!',
      'We successfully established the TraCI bridge. Physical vehicles in SUMO are now perfectly mirrored as network nodes broadcasting Wi-Fi packets inside OMNeT++.',
      'We overcame massive hurdles: TraCI API version mismatches, Python daemon ghosting, and Obstacle Shadowing crashes.',
      'Watching the first safety beacons transmit across our grid intersection made every bug worth it!'
    ],
    date: 'Jul 17, 2026',
    readTime: '4 min read',
    category: 'Milestone',
    imageUrl: 'https://images.unsplash.com/photo-1526374965328-7f61d4dc18c5?q=80&w=2070&auto=format&fit=crop',
  },
  {
    id: 'basic-traffic-simulation',
    title: 'Simulating Basic Traffic in SUMO & Connecting to OMNeT++',
    excerpt: 'Today we simulated our first basic traffic scenarios in SUMO!',
    content: [
      'Welcome to today’s update (July 16, 2026)! We took the Grid Road Network we designed previously and successfully injected our first basic traffic simulation.',
      'By defining vehicle types, randomized routes, and varying speeds, we observed the microscopic mobility of nodes interacting within the grid.',
      'Our immediate next step is to connect this active SUMO traffic with the OMNeT++ network simulator using Veins.'
    ],
    date: 'Jul 16, 2026',
    readTime: '3 min read',
    category: 'Simulation',
    imageUrl: 'https://images.unsplash.com/photo-1449824913935-59a10b8d2000?q=80&w=2070&auto=format&fit=crop',
  },
  {
    id: 'integrating-firebase-documentation',
    title: 'Integrating Firebase for Live Documentation',
    excerpt: 'Setting up Google Firebase Hosting to host this very website!',
    content: [
      'To ensure our review panels have constant access to our progress, we deployed this React/Vite blog to Firebase Hosting.',
      'By utilizing GitHub Actions and the Firebase CLI, we created a seamless CI/CD pipeline. Every time we push an update to the web repository, the site is rebuilt and deployed globally in seconds.'
    ],
    date: 'Jul 12, 2026',
    readTime: '2 min read',
    category: 'Development',
    imageUrl: 'https://images.unsplash.com/photo-1555099962-4199c345e5dd?q=80&w=2070&auto=format&fit=crop',
  },
  {
    id: 'grid-road-network',
    title: 'Designing the Grid Road Network',
    excerpt: 'We mapped out a complex Grid Road Network inside SUMO for intersection testing.',
    content: [
      'On July 10, 2026, we finalized the spatial environment for our simulations.',
      'Using NETEDIT, we designed a custom Grid Road Network. A grid layout was chosen specifically because it offers multiple intersections, varied line-of-sight conditions, and highly dynamic routing.',
      'In VANETs, intersections are critical bottlenecks where malicious nodes can do the most damage. This layout is perfect for testing our ML models.'
    ],
    date: 'Jul 10, 2026',
    readTime: '4 min read',
    category: 'Environment',
    imageUrl: 'https://images.unsplash.com/photo-1555066931-4365d14bab8c?q=80&w=2070&auto=format&fit=crop',
  },
  {
    id: 'setting-up-edgetrust-web',
    title: 'Setting up the EdgeTrust-Web Dashboard in React',
    excerpt: 'Initializing the Vite/React architecture for our front-end project documentation portal.',
    content: [
      'Documentation is just as important as the code itself. We initialized a modern Vite and React application using TypeScript to serve as our project blog and documentation hub.',
      'We designed a clean, dark-mode focused UI that highlights our architectural diagrams and timeline. This will be an invaluable resource during Guide Reviews.'
    ],
    date: 'Jul 8, 2026',
    readTime: '2 min read',
    category: 'Development',
    imageUrl: 'https://images.unsplash.com/photo-1555099962-4199c345e5dd?q=80&w=2070&auto=format&fit=crop',
  },
  {
    id: 'environment-setup',
    title: 'Development Environment & Toolchain Setup',
    excerpt: 'Phase 2 is underway. We installed SUMO, OMNeT++, and Veins on Windows 11.',
    content: [
      'On July 5, 2026, we officially completed the setup of our simulation environment, marking the beginning of Phase 2.',
      'We installed SUMO for mobility, OMNeT++ for network simulation, and Veins as the bridge. We also initialized our GitHub Organization (EdgeTrust-VANET) to ensure proper version control.',
      'We are now ready to start building the simulation world.'
    ],
    date: 'Jul 5, 2026',
    readTime: '2 min read',
    category: 'Setup',
    imageUrl: 'https://images.unsplash.com/photo-1550439062-609e1531270e?q=80&w=2070&auto=format&fit=crop',
  },
  {
    id: 'why-pki-fails-vanets',
    title: "Why standard PKI isn't enough for VANETs",
    excerpt: 'Exploring the fatal flaw of cryptographic authentication in Vehicular Ad-hoc Networks.',
    content: [
      'Public Key Infrastructure (PKI) is amazing at proving WHO sent a message. It uses digital certificates to guarantee identity.',
      'However, PKI cannot prove WHAT the message contains. If a perfectly authenticated vehicle gets hacked, it can broadcast a digitally-signed, cryptographically-perfect message containing fake crash data.',
      "This is the core reason we are building a Behavioral Trust Model. We don't just check the signature; we check the physics of the message."
    ],
    date: 'Jun 30, 2026',
    readTime: '4 min read',
    category: 'Research',
    imageUrl: 'https://images.unsplash.com/photo-1526374965328-7f61d4dc18c5?q=80&w=2070&auto=format&fit=crop',
  },
  {
    id: 'learning-sumo-omnet',
    title: 'Understanding SUMO and OMNeT++',
    excerpt: 'Spent this week learning the intricacies of SUMO for mobility and OMNeT++ for wireless networks.',
    content: [
      'Over the past week (June 25, 2026), the team engaged in a deep-dive learning sprint.',
      'We studied SUMO to learn how to define edges (roads) and nodes (junctions). We studied OMNeT++ focusing on the INET framework which models OSI layers.',
      'Understanding how MAC layers handle packet collisions is essential for extracting the communication features our ML models will rely on.'
    ],
    date: 'Jun 25, 2026',
    readTime: '5 min read',
    category: 'Research',
    imageUrl: 'https://images.unsplash.com/photo-1519389950473-47ba0277781c?q=80&w=2070&auto=format&fit=crop',
  },
  {
    id: 'project-kickoff',
    title: 'Project Kickoff & Extensive Literature Survey',
    excerpt: 'We officially started EdgeTrust-VANET! Analyzed 285 publications to understand the limitations of PKI.',
    content: [
      'June 15, 2026 marks the official kickoff of the EdgeTrust-VANET project!',
      'We started Phase 1 by conducting a massive literature survey, synthesizing insights from 285 peer-reviewed publications. Our goal was to identify critical vulnerabilities in modern VANETs.',
      'Our architecture will push security to the Edge (Roadside Units) using Machine Learning to detect anomalies in real-time. It’s time to start building.'
    ],
    date: 'Jun 15, 2026',
    readTime: '6 min read',
    category: 'Milestone',
    imageUrl: 'https://images.unsplash.com/photo-1451187580459-43490279c0fa?q=80&w=2072&auto=format&fit=crop',
  }
];
